# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Google Play"
  lane :beta do
    # increment_build_number
    gradle(task: 'clean', project_dir: './android.project')
    gradle(
      project_dir: './android.project',
      task: 'assemble',
      build_type: 'Release'
    )
    #mapping_path = File.absolute_path "../android.project/app/build/outputs/mapping/release/mapping.txt"
    upload_to_play_store(
        #mapping: mapping_path,
        track: 'beta'
    )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: 'clean', project_dir: './android.project')
    gradle(
      project_dir: './android.project',
      task: 'assemble',
      build_type: 'Release'
    )
    upload_to_play_store
  end
end

platform :ios do
  lane :beta do
    #sync_code_signing(type: "appstore")    # see code signing guide for more information
    cert(username: "andnis@gmail.com", team_name: "Anders Nissen")
    sigh(username: "andnis@gmail.com", app_identifier: "com.anissen.stoneset")
    build_app(scheme: "stoneset", project: "./ios.project/stoneset.ios.xcodeproj", include_bitcode: true)
    upload_to_testflight(username: "andnis@gmail.com", team_name: "Anders Nissen")
  end
end
