# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Google Play"
  lane :beta do
    # increment_build_number
    gradle(task: 'clean', project_dir: './android.project')
    gradle(
      project_dir: './android.project',
      task: 'assemble',
      build_type: 'Release'
    )
    upload_to_play_store(track: 'beta')
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: 'clean', project_dir: './android.project')
    gradle(
      project_dir: './android.project',
      task: 'assemble',
      build_type: 'Release'
    )
    upload_to_play_store
  end
end
